### ISSUE TITLE
Trouble training teaches

### ISSUE THREAD

**Issue by JuanDavidG1997** [karanchahal/nyu-cv-project#2]
Hi!
I am trying to train some networks (the largest ones) in Colag due too shortage of CUDA memory.
Is there any way to use this trainen models as pretrained ones?

**Comment by fruffy** [comment]
What are the models you are having trouble with?

**Comment by JuanDavidG1997** [comment]
I used an online server to traing a resnet152. I would like to use this model to disitll another network, maybe a resnet10 but in muy own PC.
Is it possible?

**Comment by fruffy** [comment]
Unfortunately that is unlikely, to distill you will have to be able to fit the larger network into your local memory. There is some work on partitioning but our repository does not make use of any of that.

**Comment by JuanDavidG1997** [comment]
Thanks!
